version: '2'

services:
    payment:
        build: 
            context: .
            dockerfile: ./Dockerfile
        image: arijmansour/pfe_payement_microservice
        hostname: pfe_payement_microservice
        restart: always
        ports:
            - "80:80"
